#!/bin/sh

# 현재 브랜치 이름 가져오기
branch_name=$(git symbolic-ref --short HEAD)

# 커밋 메시지 파일 경로
commit_msg_file=$1

# 커밋 메시지 파일이 존재하는지 확인
if [ ! -f "$commit_msg_file" ]; then
    echo "Commit message file not found!"
    exit 1
fi

# 이미 [브랜치이름] 접두사가 존재하는지 확인
# 예: [LUPG-77] test: 대학 도메인 단위 테스트 추가
if ! grep -q "\[$branch_name\]" "$commit_msg_file"; then
    sed -i '' "1s/^/[$branch_name] /" "$commit_msg_file"
fi
