name: LUPG Prod Server CD Workflows

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Docker Deploy
      - name: Docker Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ubuntu
          key: ${{secrets.PEM_KEY}}
          script: |
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/gachontable:latest
            
            EXISTING_CONTAINER_ID=$(sudo docker ps -q -f "publish=8080" -f "status=running")
            if [ ! -z "$EXISTING_CONTAINER_ID" ]; then
              sudo docker stop $EXISTING_CONTAINER_ID
              sudo docker rm $EXISTING_CONTAINER_ID
            fi

            EXISTING_CONTAINER_ID=$(sudo docker ps -q -f "publish=8080" -f "status=exited")
            if [ ! -z "$EXISTING_CONTAINER_ID" ]; then
              sudo docker rm $EXISTING_CONTAINER_ID
            fi
            
            sudo docker rm $(sudo docker ps --filter 'status=exited' -a -q) 
            sudo docker run -d -v /home/ubuntu/pinpoint-agent-2.5.3:/pinpoint-agent --log-driver=syslog  --name lupg -p 8080:8080 -p 63544:63544 -e JAVA_OPTS=-Djasypt.encryptor.password=${{secrets.JASYPT_ENCRYPTOR_PASSWORD}} ${{secrets.DOCKER_USERNAME}}/gachontable:latest
            sudo docker image prune -a -f
